### PR TITLE
Fixed fieldSelector for EventClientV1

### PR DESCRIPTION
**Pull request by tomsseisums**
Template paramater names should be PascalCase, but this was camelCase and didn't actually update the query param. This PR fixes that.

### CODE REVIEW

**Comment by tomsseisums** [comment]
A quick release would also be great. 🙏

**Comment by tintoy** [comment]
Thanks, nice catch!

**Comment by tomsseisums** [comment]
When could we expect a release that would include this one?

**Comment by tintoy** [comment]
Working on it 🙂 

Small compile error (need to update `IPodClientV1` as well as `PodClientV1`) - I'm doing that now.

**Comment by tintoy** [comment]
Published [v2.4.6](https://app.travis-ci.com/github/tintoy/dotnet-kube-client/builds/237952581) 😉

(may take a while to become visible on NuGet; I think their indexing process is asynchronous)

**Pull request merged**
