### PR TITLE
Update Log method signature on IPodClientV1 to match PodClientV1

### PR DESCRIPTION
**Pull request by tintoy**
Relates to #141.

CC: @tomsseisums

### CODE REVIEW

**Review by tomsseisums — COMMENTED** [review]
Oh, right. That's what you get when editing in GitHub. 🙄

**Comment by tintoy** [comment]
All good - building now! 🙂

**Comment by tintoy** [comment]
Published [v2.4.6](https://app.travis-ci.com/github/tintoy/dotnet-kube-client/builds/237952581) 😉

(may take a while to become visible on NuGet; I think their indexing process is asynchronous)

**Comment by tomsseisums** [comment]
There's no tag for it in GH, though. Same as v2.4.4.

**Comment by tomsseisums** [comment]
And also for whatever reason, v2.3.5 is shown as the latest release in GitHub.

**Comment by tintoy** [comment]
I think you explicitly have to promote a tag to be a release by publishing it as one.

I've just published it here: https://github.com/tintoy/dotnet-kube-client/releases/tag/v2.4.6

**Pull request merged**
