### PR TITLE
Initial port of KubeClient.Extensions.DataProtection

### PR DESCRIPTION
**Pull request by tintoy**
This code has been ported from https://github.com/rriverak/KubeClient.Extensions.DataProtection (thanks, @rriverak!).

Note that, at this, stage, it is a work in progress; we need to decide on strategies for:

- [x] Concurrency
  - [x] Basic synchronisation of access to the `SecretV1` instance used by the key store  
          _This is handled by the secret manager._
  - [x] What happens when underlying Secret is changed by one client, and another is in the middle of loading secrets?  
          _The store operates on a snapshot of the underlying Secret's data._
  - [ ] What happens when 2 clients attempt to create the secret simultaneously?
  - [x] Updating the Secret will result in the change-notification handler firing; this means the Secret is always re-loaded after being created. Is this OK, or would we want to suspend notifications while we know we are modifying the Secret?
- [x] Handling of common edge-cases / error conditions
  - [x] Secret has been deleted
  - [x] Secret has been deleted and then re-created
  - [x] Secret does not exist and creation fails
  - [x] Secret values contain invalid data (e.g. invalid Base64-encoded data, or invalid XML).

Relates to tintoy/dotnet-kube-client#94.

### CODE REVIEW

**Comment by rriverak** [comment]
The subject of **Concurrency** is managed by DataProtection by default.
We actually implement only a IXmlRepository. That's just the persistence logic.
  
Our `PersistKeysToKubeSecret` function only persists the XML Keys. (like Filesystem, Redis or AuzureBlob) 

If you want to control the KeyManagement flow you need to the `IKeyManager`.
That depends heavily on your Scenario.

```csharp
services.AddDataProtection()
.PersistKeysToKubeSecret(...)
.DisableAutomaticKeyGeneration(); // ReadOnly Keyring
```
For example, by default a single keyring is generated for each content path. [ms-doc](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.2#setapplicationname)
To share a keyring between applications, SetApplicationName must be used.

```csharp
services.AddDataProtection()
.PersistKeysToKubeSecret(...)
.SetApplicationName("shared app name"); // Shared Keyring
```

For your Querstions we need to look a bit deeper in the `IXmlRepository` usage.

**Read**
```csharp
IReadOnlyCollection<XElement> GetAllElements()
```
The keymanager request only on startup the Keys with this Method. 
All Keys will stored in protected Memory by the DataProtection lib. 
This function is only recalled all 24h or on a Key-Invalidation. [ms-doc](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-management?view=aspnetcore-2.2#automatic-key-ring-refresh)

**Insert / Update**
```csharp
void StoreElement(XElement element, string friendlyName)
```
By default the `friendlyName` is just the ID of the key. [code-link](https://github.com/aspnet/AspNetCore/blob/7b0b2980dc6ffb860f2bcd71868d98d85c7d35b6/src/DataProtection/DataProtection/src/KeyManagement/XmlKeyManager.cs#L421)
If the value is not unique, we have completely different problems.

However, the ability to update still needs to be implemented [here](https://github.com/tintoy/dotnet-kube-client/blob/48f79a853702d756d3b9d2b9d37dc11156c9363d/src/KubeClient.Extensions.DataProtection/KubeSecretXmlRepository.cs#L144). (only the Key-Revoke updates a XMLElement with a flag)

There is no way to delete keys because otherwise existing data will never be decrypted and migrated to a new key.

**Comment by tintoy** [comment]
Thanks! This is exactly the detail I was going to go looking for :)

In that case I may skip locking and simply make a local copy of the reference to the class field (so future maintainers understand they’re working with an isolated copy but the original reference could be replaced at any time by the event handler.

What if the underlying Secret resource is deleted after the app is started? Should we attempt to re-create it if the patch fails because the resource no longer exists?

**Comment by helmsb** [comment]
Howdy, just curious if there are any plans to revisit this? I am in need of this exact functionality. Happy to help resolve merge conflicts or anything that might help get this across the finish line.

**Comment by tintoy** [comment]
Sorry for the delay; this is proving quite difficult to test without a live K8s instance (and I'm trying to avoid adding tests that can't be run during CI). Still working on it, but it's slow going 😂

**Comment by tintoy** [comment]
Ok, I think I have a working solution for testing; I'll tidy it up tomorrow morning and then I think we should be good to go 🙂

**Comment by tintoy** [comment]
Finally! Sorry it's taken so long 😄

**Pull request merged**
