### PR TITLE
Fix deserialization issues for errors in ObserveEvents

### PR DESCRIPTION
**Pull request by typusomega**
Hi @tintoy,

we had some issues with deserialization while watching for events.
If, for example, you set a specific resourceversion which is gone, the event was deserialized into `ResourceEventV1<TResource>` while it actually was a different JSON object.

We did not want to create a deserialization class for this, so we used `JToken` to keep the overhead as small as possible.

Would be nice if you could merge soon.

Best regards,
Jens

### CODE REVIEW

**Comment by tintoy** [comment]
Hi - good catch, and thanks!

Sorry for the late reply (I'm in AU).

**Comment by tintoy** [comment]
Building release packages now:

https://travis-ci.org/tintoy/dotnet-kube-client/builds/402918518

**Comment by tintoy** [comment]
Oops - build versioning weirdness; trying again...

**Comment by tintoy** [comment]
Ok - v2.1.5 of packages have been published to NuGet (unfortunately, it may take up to 20 minutes for NuGet to index the packages so they're available to install).

**Comment by typusomega** [comment]
Hey,
thanks for the fast merge!

**Comment by tintoy** [comment]
I really like what you guys have done with custom resource clients BTW. I've been meaning to look into the semantics for resource versions but I see you folks have already figured that out!

**Pull request merged**
